version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/build:/client
    ports:
      - 80:80
    networks:
      - mern-network
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - server:/server
    restart: on-failure
    ports:
      - 3001:3001
    networks:
      - mern-network
    env_file:
      - ./server/.env.production
    environment:
      - CLIENT_URL=http://192.168.99.100:80/#
    depends_on:
      - db

  db:
    image: mongo
    restart: on-failure
    volumes:
      - data-volume:/data/db
    ports:
      - 27017:27017
    networks:
      - mern-network
    command: ["mongod", "--auth"]

networks:
  mern-network:
    driver: bridge

volumes:
  data-volume:
    driver: local
  server:
  client:
