export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

export const UPDATE_PURCHASED_BOOKS = "UPDATE_PURCHASED_BOOKS"

export const FOLLOW_BOOK = "FOLLOW_BOOK"
export const FOLLOW_BOOK_CANCEL = "FOLLOW_BOOK_CANCEL"
