export const GET_BOOKS_REQUEST = "GET_BOOKS_REQUEST";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAILURE = "GET_BOOKS_FAILURE";

export const GET_BOOK_DETAILS_REQUEST = "GET_BOOK_DETAILS_REQUEST";
export const GET_BOOK_DETAILS_SUCCESS = "GET_BOOK_DETAILS_SUCCESS";
export const GET_BOOK_DETAILS_FAILURE = "GET_BOOK_DETAILS_FAILURE";
export const GET_BOOK_DETAILS_RESET = "GET_BOOK_DETAILS_RESET";


